#!/bin/bash

# Clazy
CLAZY_FIXIT="\
fix-qdatetime-utc \
fix-qgetenv \
fix-missing-qstringref \
fix-auto-unexpected-qstringbuilder \
fix-old-style-connect \
fix-qlatin1string-allocations \
fix-fromLatin1_fromUtf8-allocations \
fix-fromCharPtrAllocations"

git pull --rebase
mkdir build
cd build
cmake .. 2> /dev/null > /dev/null

# Find all git sub modules
MODULES=$(find .. -type d -name .git)
echo MODULES: $MODULES

rm /patches/* || echo No patches to remove

DIR=$PWD

for fixit in $CLAZY_FIXIT; do
    rm -rf ./* || echo
    export CLAZY_FIXIT="$fixit"
    cmake .. 2> /dev/null > /dev/null
    echo Apply ${fixit}
    CLAZY_FIXIT="$fixit" warningdb /tmp/dummy --no-print
    # Patch the submodules too
    for mod in $MODULES; do
        cd ${mod}/../
        echo IS IN ${PWD}
        git commit -a -m "quality: Apply Clazy $fixit changes (autogenerated)"
        if [ $? == 0 ]; then
            echo Saving patch /patches/$(basename $PWD)/${fixit}.patch
            mkdir -p /patches/$(basename $PWD)/
            git show --patch HEAD > /patches/$(basename $PWD)/${fixit}.patch
        fi
        cd $DIR
    done
done
